# Generated by Django 4.2.19 on 2025-02-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='age_gte_18'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(check=models.Q(('phone_number__regex', '^\\+?[0-9]{10,15}$')), name='valid_phone_number'),
        ),
    ]
